### ISSUE TITLE
Mac French Keyboard the key "/" for Fraction has a wrong behavior

### ISSUE THREAD

**Issue by Chrisb0606** [arnog/mathlive#1459]
Hello,
I also face exactly the same issue but this time with a French Mac Keyboard.
When I use the "/" with the numeric keypad it behaves as a fraction but when I use the "/" in the "latin" layout it displays a "/" as a text (not a fraction).
I use an AZERTY French Mac Keyboard. I've tested with the Mac US Keyboard setting it works well.
I ve figured out that the keycodes are different in FR or US MacKeyboard.
On the US Mac Keyboard :
- 111 for the "/" on numeric pad (works  as a Fraction as expected)
- 191 for the "/" on latin layout  (works  as a Fraction as expected)
On the French Mac Keyboard :
- 111 for the "/" on numeric pad (works  as a Fraction as expected)
- 58 for the "/" on standard keyboard (doesn't work as a Fraction but as a "/"  text )

Thanks for your help,
Chris

_Originally posted by @Chrisb0606 in https://github.com/arnog/mathlive/issues/974#issuecomment-1131523146_

**Comment by arnog** [comment]
I can't reproduce this.

Just to be clear, you are holding the shift key and pressing the key second to the left from the right shift key (circled in red below)?

<img width="622" alt="Screen Shot 2022-05-19 at 07 50 42" src="https://user-images.githubusercontent.com/760798/169326084-4a82e372-4306-465a-bc16-2fab81a26d81.png">

Is your system locale French (i.e. are the menus displayed by the system in French)?

Does this also happen if you press the "aze" keys before pressing the "/" key?

How did you configure the mathfield? Did you set its locale? Did you call `setKeyboardLayout()` or `setKeyboardLayoutLocale()`?

**Comment by Chrisb0606** [comment]
Hello,
It's exactly what I've done.
- When I press the "aze" the behavior is the same.

Thanks to your comment about menu displayed in French or not, I've explored a little bit more.
Actually, my MacOS is in French and this bug appears : 
- With an english browser (I use Firefox Developer edition only availabale in English) : each time I fill the mathfield with a "/" (any of them) the first time it behaves correctly, then I delete the fraction and I fill again with the "/" (the one with the shift key) and then it behaves wrongly  : see video attached : https://user-images.githubusercontent.com/47278321/169342344-baf47d9c-76e3-41f3-9051-9fcb22ac6c51.mov
- If I use a French language Browser it happens less often, but it happens when I change the DOM : I remove the mathfield node and I append it again (I've implemented a kind of replay action that reloads a part in the DOM where the mathfield is). In this case after a mathfield removal and an append in the DOM, fraction behaves incorrectly in any event.

Concerning my implementation, I didn't use setKeyboardLayout neither setKeyboardLayoutLocale. Please find below the code I use to append a MathField in my DOM: 
```
 answerMathField = new window.MathfieldElement();
  //Set options to mathfield
  answerMathField.setOptions({
    defaultMode: "math",
    virtualKeyboardMode: "manual",
    virtualKeyboards: "numeric",
    smartFence: false,
    fontsDirectory: "../fonts/",
    soundsDirectory: "../sounds/",
  });
  console.log("MathfieldElement");
  answerMathField.setAttribute("virtual-keyboard-mode", "manual");
  answerMathField.setAttribute("id", id);




  answerMathField.setAttribute("style", "font-size: 20px;");
...
documentNode.append(answerMathField);
```
Thanks a lot.
Chris

**Comment by Chrisb0606** [comment]
In the English Browser : apple.en-intl
In the French Browser : apple.en-intl
I use the version 0.69.11

**Comment by arnog** [comment]
OK. Can you try with the current version? I believe this issue has been addressed here: https://github.com/arnog/mathlive/commit/c20f71c1b66d68dd74b366ae42200aacaada2e4e

**Comment by Chrisb0606** [comment]
I've installed the 0.72.3 and it seems to fix the first bug.

For the second bug (when I remove and append a mathfield on a page), the bug still there. Few  removal and append are enough to make the "/" reappears (see video)

https://user-images.githubusercontent.com/47278321/169360311-6fa00264-8342-4f20-aee9-9b6457780811.mov

**Comment by arnog** [comment]
Could you share some code of what you are doing (how are you removing the mathfield and how are you adding it back)?

**Comment by Chrisb0606** [comment]
I've isolated it in : https://codesandbox.io/s/mathfield-bug-when-remove-append-1om68r?file=/src/index.js

Few clicks on the button, then use a "/" (with the shift key) make the bug occurs.
Thanks,

**Comment by arnog** [comment]
OK,  I got it, thanks. I see what the problem is. I'm working on a  fix.

**Comment by Chrisb0606** [comment]
Thanks a lot. It Works like a charm now on English browser and French as well.
Thanks for your great job !
