### ISSUE TITLE
Can't change text color when highlighting text

### ISSUE THREAD

**Issue by LinGrin** [arnog/mathlive#1562]
## Description

Setting the `--on-highlight` variable is supposed to set the color of the text when it's highlighted. Currently this doesn't work.

## Steps to Reproduce

1. open the basic example
2. modify the css to set the `--on-highlight` variable to a color of your choice
3. run the example and highlight some text in the math-field
4. the text will stay the color it was and not change color when highlighted

### Expected Behavior

text color should change on highlight to the set color

[Is this a regression: did it use to work in a previous version?]

### Environment

**MathLive version**
I'm on latest at the moment, or commit 9d769e03c59dd98ae07ca72de6f358eb9b31411b

**Operating System** [macOS, Windows, iOS. Include the version]
I am using a Mac, v12.4

**Browser** [Safari, Chrome, IE, Firefox, etc... Try several browsers and note
if there are differences between browsers. Include the version number of the
browsers.] 
This happens in Chrome and Firefox

**Comment by arnog** [comment]
The CSS variables are now called `--selection-background-color` and `--selection-color`

**Comment by LinGrin** [comment]
Thanks for adding this! However it looks like placeholder box colors don't change to match: 
<img width="127" alt="image" src="https://user-images.githubusercontent.com/43445438/182241303-0e263bb8-5254-4550-be0c-219c936d94aa.png">
is that expected?

**Comment by arnog** [comment]
Yes, there is a `--placeholder-color` variable, although it doesn't have a "selected" variant.
On second thoughts, it would make more sense for the placeholder color to use the `--selection-color` when selected. I've pushed a fix to the main branch.

**Comment by LinGrin** [comment]
It's almost completely fine now, however the placeholders still don't change colors when they are highlighted from using the arrow keys to navigate to the placeholder, or when using the mouse to select just a placeholder, see:
<img width="161" alt="image" src="https://user-images.githubusercontent.com/43445438/182380950-0d6f9383-f584-47ad-87a1-8d6e8153eda0.png">

but highlighting the entire fraction via mouse does work

**Comment by LinGrin** [comment]
Should I make a new issue for the above comment?

**Comment by arnog** [comment]
I've  checked in a fix to the main branch. Open a new issue if you find some other problems.
