### ISSUE TITLE
Maximum call stack size error when press 'delete' button in empty mathfield

### ISSUE THREAD

**Issue by Paosder** [arnog/mathlive#323]
**Describe the bug**
When press 'Delete' button in empty mathfield, maximum call stack size error occurs.

**To Reproduce**
1. Go https://mathlive.io/
2. See any examples and clear mathfield using 'Backspace' or 'delete' button
3. Press 'delete' button
4. Here comes `range error: maximum call stack size exceeded.`!

**Expected behavior**
With no errors, nothing happens.

**Screenshots**
![mathlive-error](https://user-images.githubusercontent.com/20926881/70962655-3fda2e00-20c9-11ea-9883-cf69b545fa6b.PNG)

**Environment**
- Device: PC
- OS: [Windows 10]
 - Browser [Chrome]
 - Version [0.33]

**Comment by Paosder** [comment]
@arnog Thank you to hotfix this issue. however in 0.33.1, the version that you fixed this issue, has no bundled js file in `dist` directory, neither font files too. I cannot load mathlive since upgraded to 0.33.1.

**Comment by arnog** [comment]
Hmmm... Not exactly sure what happened, but it should be fixed now in 0.33.2

**Comment by shenzhuxi** [comment]
Hi @arnog 
This problem still exists if use $text('ASCIIMath'). 
BTW, it's not only caused by using 'delete' button but also by pressing any key after '^' was pressed.

**Comment by arnog** [comment]
I can't reproduce this problem. I went to mathlive.io, emptied the field, typed "abc", positioned back to the beginning, then typed the "delete" key. It worked. I typed "^", then pressed "2". It worked.

Please provide more info, including which version of MathLive you are using, and specific steps or code necessary to reproduce what you are seeing.

**Comment by shenzhuxi** [comment]
version: 0.35.1

 <script type="module">
      import MathLive from 'mathlive/dist/src/mathlive.js';
      const mf = MathLive.makeMathField('mathfield', {
        smartMode: true,
        virtualKeyboardMode: 'manual',
        onContentDidChange: mf => {
          console.log(mf.$text('ASCIIMath'));//**You need to output with ASCIIMath to reproduce this problem.**
        },
      });
  </script>

Here is the fix: 
--- a/dist/src/editor/outputASCIIMath.js
+++ b/dist/src/editor/outputASCIIMath.js
@@ -73,6 +73,7 @@ export function toASCIIMath(atom, options) {
         let result = '';
         if (atom.length === 0) return '';
         if (atom[0].type === 'first') atom.shift();
+        if (atom.length === 0) return '';

For the '^' problem, I just figured out that Mathlive considers it as "msubsup" instead of power. 
Atom {mode: undefined, type: "msubsup", body: "​", color: undefined, backgroundColor: undefined, …}
"mode: undefined" causes infinite loop in outputASCIIMath.js 
@@ -88,6 +89,7 @@ export function toASCIIMath(atom, options) {
                 result += toASCIIMath(atom[i], options);
                 i++;
             }
             result += toASCIIMath(atom.slice(i), options);//**infinite loop here**

**Comment by arnog** [comment]
OK, got it. It's not related to deleting, as the original bug report indicate, but it's an infinite loop that happens under different circumstances. Thanks for the additional info and for the fix. I've opened #394 to track the issue. I'd be happy to take a PR, otherwise I'll merge in your changes manually. Either way, thank you.
