### ISSUE TITLE
Can't use keyboard ^ shortcut for exponent

### ISSUE THREAD

**Issue by jhiswin** [arnog/mathlive#448]
Typing ^ in MathField doesn't allow the exponent to pop up.  Cursor disappears.  If you try to type ^ a couple more times this error pops up:
TypeError
Cannot read property 'array' of null

Problem appears starting from 0.50.1
0.35.1 worked

Chrome 80 Windows

**Comment by oliverstefanov** [comment]
I was just going to signal this bug as well. Would also love to see a fix. Thanks!

**Comment by arnog** [comment]
It is fixed in MathLive 0.50.7

**Comment by jhiswin** [comment]
Confirmed working.  Just want to let you know the demos on mathlive.io and elsewhere still have this bug.

**Comment by arnog** [comment]
Great! And I've updated mathlive.io now.
