### ISSUE TITLE
azerty keyboard

### ISSUE THREAD

**Issue by alexandre-garrec** [arnog/mathlive#5]
## Description
Is it possible to add support for azerty keyboard ?

## Exemple
shift + 6 = ^ ( **in querty** )
shift + 6 = 6 ( **in azerty** )

**Comment by arnog** [comment]
As a temporary workaround, Ctrl+6 will give you a superscript, Ctrl+- will give you a subscript and Ctrl+5 will switch between the two.

**Comment by arnog** [comment]
Should work now, although I don't have an AZERTY keyboard around to test it with. The "^" key should behave as expected, in addition to the Ctrl+6 shortcut mentioned above.

**Comment by tom-s** [comment]
That doesn't seem to work, i still get ^ when I type shift + 6 on my azerty keyboard.
FYI im using the master branch of this project.
