### ISSUE TITLE
Firefox Nth root symbol missing top line

### ISSUE THREAD

**Issue by manstie** [arnog/mathlive#934]
## Description

When writing the Nth root symbol on Firefox, the element is sometimes cut off by the container so you can't see the top line.

Firefox 88.0.1 (64-bit) on Windows:
![image](https://user-images.githubusercontent.com/12475567/117561703-bc5d1a80-b0cb-11eb-8b86-146fd8a8af53.png)
![image](https://user-images.githubusercontent.com/12475567/117562296-7c4c6680-b0d0-11eb-8354-937ab43edb53.png)
It sometimes appears when other symbols exist in the equation:
![image](https://user-images.githubusercontent.com/12475567/117562302-88d0bf00-b0d0-11eb-8170-53c43f895add.png)

Chrome 90.0.4430.93 (Official Build) (64-bit) on Windows:
![image](https://user-images.githubusercontent.com/12475567/117561724-ef071300-b0cb-11eb-96f0-cc0a01774951.png)

## Steps to Reproduce

1. Empty the input
2. Insert a Nth root symbol

### Actual Behavior

The `sqrt-line` element is cropped out in most equation scenarios.

### Expected Behavior

The top line should not be cut off by the math container.

### Environment

https://cortexjs.io/mathlive/guides/virtual-keyboards/

Under the section "Customizing the appearance of the virtual keyboard toggle" with the red keyboard icon.

**Operating System** Windows 10 Pro (Build 19042.928)

**Comment by arnog** [comment]
I just published mathlive 0.64 which I believe may address this issue.
Could you try it on your configuration and let me know if that's not the case (cortexjs.io has been updated with the new version)?

**Comment by manstie** [comment]
Same page, I did notice the change for when writing `\sqrt` + `enter` it prints the empty box to fill, which is nice - but this kind of stuff is still happening:
![image](https://user-images.githubusercontent.com/12475567/117656561-14c71180-b1cb-11eb-82d3-af47f21199b4.png)

`\begin{equation*} \sqrt{555} \end{equation*}`

![image](https://user-images.githubusercontent.com/12475567/117656481-fb25ca00-b1ca-11eb-91e3-ee10d3fbd163.png)

`\begin{equation*} \sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{55555}}}}}}} \end{equation*}`

**Comment by manstie** [comment]
It is `Basic`

**Comment by arnog** [comment]
That appears to be a rendering bug specific to the basic (software) renderer in Firefox. Mozilla is in the process of switching their renderer to a new version codename Quantum/WebRender which does not exhibit this problem. I think they are unlikely to fix it in their basic renderer, and I can't seem to find a workaround that works. This is a problem that will go away over time once they finish rolling it out to all their users. In the meantime, you can try to enable it manually (your hardware may not be supported, though), by following the instructions here: https://www.askvg.com/tip-how-to-enable-or-disable-new-webrender-feature-in-mozilla-firefox/
